### PR TITLE
acism: Add missing glib dependency

### PR DESCRIPTION
**Pull request by cryptomilk**
This library uses g_ascii_tolower()

### CODE REVIEW

**Comment by vstakhov** [comment]
This library is used as module and hence it doesn't need any dependencies itself.

**Comment by cryptomilk** [comment]
At least my compiler thinks different:

[   44s] cd /home/abuild/rpmbuild/BUILD/rspamd-1.4.0/build/contrib/librdns && /usr/bin/cc  -DHAVE_CONFIG_H -DLINUX -D_GNU_SOURCE -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/hire
dis -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0 -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src/libutil -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src/libserver -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src/libmime -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src/libstat -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/src/libcr
yptobox -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/libucl -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/linenoise -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/uthash
 -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/http-parser -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/libottery -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/xxhash -
I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/cdb -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/snowball/include -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/librdns -I/
home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/aho-corasick -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/lc-btrie -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/lpeg -I/home
/abuild/rpmbuild/BUILD/rspamd-1.4.0/build/src -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/build/src/libcryptobox -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gmi
me-2.6 -I/home/abuild/rpmbuild/BUILD/rspamd-1.4.0/compat -I/usr/include/luajit-5_1-2.0  -g -O2 -fstrict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2
-fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -D_GNU_SOURCE -pthread -D_LARGEFILE64_SOURCE -pthread -DOPENSSL_LOAD_CONF -DOPENSSL_LOAD_CONF -fPIC  -W -Wall -W
pointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wno-pointer-sign -Wstrict-prototypes -Wno-unused-const-variable -Wno-sign-compare -std=c11 -O2 -g -DNDEBUG
 -o CMakeFiles/rdns.dir/curve.c.o   -c /home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/librdns/curve.c
[   44s] CMakeFiles/rspamd-actrie.dir/acism.c.o: In function `acism_lookup':
[   44s] /home/abuild/rpmbuild/BUILD/rspamd-1.4.0/contrib/aho-corasick/acism.c:37: undefined reference to `g_ascii_tolower'

**Comment by vstakhov** [comment]
Then you use some strange link flags in your linker. In theory, I have no objections about linking glib to this library I just don't see anything useful from this as actrie is not intended for public usage - that's just LGPLv3 requirement...

**Comment by cryptomilk** [comment]
These are the flags used by the openSUSE distribution to build a RPM package:

```
-DCMAKE_C_FLAGS=-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -
D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables
-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now
```

I do not see something fancy here.

**Comment by vstakhov** [comment]
`-Wl,--no-undefined` is the culprit. I don't see any point in this flag when linking modules.

**Comment by cryptomilk** [comment]
But then you should use MODULE and not SHARED ...

```add_library(rspamd-actrie MODULE ${AHOCORASICSRC})```

**Comment by cryptomilk** [comment]
Thanks, I've opened https://bugzilla.opensuse.org/show_bug.cgi?id=1012388

**Pull request merged**
