### PR TITLE
[Rework] Remove systemd socket activation (Fixes #759)

### LINKED ISSUE #759: Fix systemd socket activation fiasco
Remaining known issues with systemd socket activation are:

1) Controller listens on IPv6 only, which means that controller commands like `rspamc stat` might not work without passing `-h` depending on system configuration.
2) Socket file will fail on systems without IPv6 support

~~I believe I can fix both. Unfortunately, it seems that we will need two `.socket` files where we used to have one, which is potentially disruptive & confusing to users. But I think the change is worth it & we could try manage this as best possible in packaging.~~ Actually multiple socket files results in unpredictable behaviour, and stuff we need to deal with this is not available in versions of systemd we want to support, so just give up all hope & rip out socket activation completely?

3) Socket activation is unfamiliar & confusing to many users.

Is not really something we can fix. Could be addressed somewhat by improving documentation. If we rip out socket activation it becomes a non-issue.

### PR DESCRIPTION
**Pull request by fatalbanana**
Confirmed to provide a clean & reboot-proof upgrade-path on CentOS 7, Debian Jessie & Ubuntu Xenial- so I suppose we can ship it.

TODO:

- Update documentation
- Update rspamd-build-scripts
- rmilter

### CODE REVIEW

**Comment by fatalbanana** [comment]
Fixes #430 
Maybe fixes #452
Fixes #748 
Fixes #740

**Comment by Glandos** [comment]
Could you please at least keep the .socket file, without enabling it at install. I have both IPv4 and IPv6, and I experienced no issue with that.
Socket activation is great for fast boot, which is important in my use case. I don't reboot often, but when I do, I appreciate the low 2 minute downtime.

**Comment by fatalbanana** [comment]
Packaging will likely break socket-activated setups on upgrade so providing this as an option requires some careful testing with/without socket activation on different platforms (and probably changes to packaging) which I don't have time for.

**Comment by jhass** [comment]
I'm not sure I follow. Either the package installs a socket activated setup or it doesn't. Then on upgrade

* It does nothing if it's not common for the distro to handle updates (eg. Archlinux).
* It does a `systemctl daemon-reload`.
* It does a `systemctl restart rspamd.service` for non-socket activated setups.
* It does a `systemctl stop rspamd.server` for socket activated setups.

**Comment by fatalbanana** [comment]
Packaging maintained within rspamd project (Debian/RPM) does _not_ use socket-activation anymore (and we don't recommend using it). Something like `restart rspamd.service` happens on upgrade- which breaks socket-activated setups. Packaging also enables `rspamd.service` to run on startup- which breaks socket-activated setups. 3rd party packagers can still do whatever they like.

**Pull request merged**
