### PR TITLE
[Fix] Fix empty threshold check in greylisting module

### PR DESCRIPTION
**Pull request by moisseev**

### CODE REVIEW

**Comment by fatalbanana** [comment]
It seems it shouldn't matter either way but this code looks strange indeed.

**Comment by moisseev** [comment]
@fatalbanana I believe `a == a` is always true in Lua. Am I wrong?

**Comment by fatalbanana** [comment]
You're not wrong and there's no point in such a comparison, the effects of this are just not harmful.

~~~lua
if settings['greylist_min_score'] then
  -- we set greylist_min_score from config
else
  -- we try get it from metric
  local greylist_threshold = rspamd_config:get_metric_action('greylist')
  if true then
    -- maybe greylist_threshold is nil but doing the assignment doesn't hurt
    settings['greylist_min_score'] = greylist_threshold
  end
end
~~~

**Comment by vstakhov** [comment]
`a == a` is not true in case of NaN. That's the point of this check.

**Comment by fatalbanana** [comment]
So... I should not have merged this I suppose. ;) I wonder why would it be NaN though.

**Comment by vstakhov** [comment]
It is NaN if action threshold is not set.

**Pull request merged**
